build:
	gcc oets.c -o oets -lpthread -lm -Wall
	gcc shear.c -o shear -lpthread -lm -Wall
	gcc merge.c -o merge -lpthread -lm -Wall
	gcc merge_paralel_all.c -o merge_paralel_all -lpthread -lm -Wall
	gcc parallel_binary_search.c -o parallel_binary_search -lpthread -lm -Wall
clean:
	rm -rf oets shear merge parallel_binary_search
